version: '2.1'

services:
  myapp:
    image: myapp
    build:
      args:
        source: bin/Release/PublishOutput/
      context: .\myapp
      dockerfile: Dockerfile
    ports:
      - "80"
networks:
  default:
    external:
      name: nat